/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/arsenal_presets": {
    get: {
      parameters: {
        query: {
          name?: parameters["rowFilter.arsenal_presets.name"];
          items?: parameters["rowFilter.arsenal_presets.items"];
          date_created?: parameters["rowFilter.arsenal_presets.date_created"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["arsenal_presets"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** arsenal_presets */
          arsenal_presets?: definitions["arsenal_presets"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          name?: parameters["rowFilter.arsenal_presets.name"];
          items?: parameters["rowFilter.arsenal_presets.items"];
          date_created?: parameters["rowFilter.arsenal_presets.date_created"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          name?: parameters["rowFilter.arsenal_presets.name"];
          items?: parameters["rowFilter.arsenal_presets.items"];
          date_created?: parameters["rowFilter.arsenal_presets.date_created"];
        };
        body: {
          /** arsenal_presets */
          arsenal_presets?: definitions["arsenal_presets"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  arsenal_presets: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    name: string;
    items?: string;
    date_created?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** arsenal_presets */
  "body.arsenal_presets": definitions["arsenal_presets"];
  "rowFilter.arsenal_presets.name": string;
  "rowFilter.arsenal_presets.items": string;
  "rowFilter.arsenal_presets.date_created": string;
}

export interface operations {}

export interface external {}
